### ISSUE TITLE
Add tracking of 'hasChanged' and 'hasBlurred' states

### ISSUE THREAD

**Issue by paulsorge** [andyrichardson/fielder#21]
# About
It would be great to have the option to mark fields as touched after the first change and not on blur only. I have the requirement to show error messages immediately when validation fails in my current project and I guess that is not possible right now, correct?
That's it. ;)

**Comment by andyrichardson** [comment]
Hey @Shrokk thanks for the suggestion.

The current way of doing this would be:

```tsx
const [fieldProps, fieldMeta] = useField({
  name: 'field',
  validateOnChange: true,
  validate: validateField,
});

useEffect(() => {
  if (fieldProps.value) {
    onBlur();
  }
}, [fieldProps]);
```

There are some caveats with this however - I'll see what I can do about adding an option such as `touchOnChange`

Edit: another option is for Fielder to track touched and changed states separately. 

Touched = blurred
Changed = value !== initialValue

**Comment by paulsorge** [comment]
Hey, thanks for your response. Unfortunately this would not work for pre-filled forms (which I have to deal with a lot) without adding additional checks to compare the fieldProps.value to the initial form values.

Anyways, I would appreciate that feature a lot. I am just preparing the rewrite of a more complex front-end app in react and would really like to use your package for form handling because I really like the approach you chose.

**Comment by andyrichardson** [comment]
> Unfortunately this would not work for pre-filled forms

I'll see what I can do :+1:

In the meantime, you could use `initialTouched`

```tsx
const [fieldProps, fieldMeta] = useField({
  name: 'field',
  initialTouched: true,
  validateOnChange: true,
  validate: validateField,
});
```

Or if you only want to validate on change, you can intercept change events and update your validation conditional.

```tsx
const fieldChanged = useRef(false);
const [fieldProps, fieldMeta] = useField({
  // ...
});

const handleFieldChange = useCallback((e) => {
  fieldChanged.current = true;
  fieldProps.onChange(e);
}, []);

// ...

<input type="text" {...fieldProps} onChange={handleFieldChange} />
{fieldChanged && fieldMeta.error && <ErrorMessage error={fieldMeta.error} />}
```

**Comment by andyrichardson** [comment]
This will be out for the next release

**Comment by andyrichardson** [comment]
@Shrokk this is now live 🔥 🔥 🔥 

Thanks for the suggestion and let me know if you have any issues with it!

[Updated docs are here](https://fielder.andyrichardson.dev/guides/validation#presenting-validation)
