### ISSUE TITLE
Textarea onChange error

### ISSUE THREAD

**Issue by paulsorge** [andyrichardson/fielder#24]
Making changes to a textarea field throws the following error
`Uncaught Error: Unsupported input elemen at u (useField.ts:153)`
   
I think a check for it is missing in the `getElementType` function in `useField.ts`. Or are textareas not supported yet for some reason?

**Comment by andyrichardson** [comment]
> I think a check for it is missing in the getElementType function in useField.ts. 

Sounds about right - will fix this for the next release :+1:
